    # Generated by Django 4.2.5 on 2023-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_completo', models.CharField(max_length=150)),
                ('RG', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=150)),
                ('Data_nascimento', models.CharField(max_length=100)),
                ('Data_de_expedição', models.CharField(max_length=150)),
                ('Orgão_emiçor', models.CharField(max_length=100)),
                ('Estado_civil', models.CharField(max_length=150)),
                ('Nome_da_Mãe', models.CharField(max_length=100)),
                ('Empresa', models.CharField(max_length=150)),
                ('Regime_de_trabalho', models.CharField(max_length=100)),
                ('Profição', models.CharField(max_length=150)),
                ('Salario_bruto', models.CharField(max_length=100)),
                ('Salario_liquido', models.IntegerField()),
                ('Endereço_residencial', models.CharField(max_length=100)),
                ('Numero', models.CharField(max_length=150)),
                ('Bairro', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=150)),
                ('Estado', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=100)),
            ],
        ),
    ]
