# Generated by Django 4.2.5 on 2023-09-28 17:39

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_completo', models.CharField(max_length=50)),
                ('RG', models.CharField(max_length=20)),
                ('CPF', models.CharField(max_length=20)),
                ('Data_nascimento', models.CharField(max_length=15)),
                ('Data_de_expedição', models.CharField(max_length=15)),
                ('Orgão_emiçor', models.CharField(max_length=10)),
                ('Estado_civil', models.CharField(max_length=10)),
                ('Nome_da_Mãe', models.CharField(max_length=50)),
                ('Empresa', models.CharField(max_length=20)),
                ('Regime_de_trabalho', models.CharField(max_length=20)),
                ('Profição', models.CharField(max_length=20)),
                ('Salario_bruto', models.CharField(max_length=20)),
                ('Salario_liquido', models.IntegerField()),
                ('Endereço_residencial', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=10)),
                ('Bairro', models.CharField(max_length=20)),
                ('Cidade', models.CharField(max_length=20)),
                ('Estado', models.CharField(max_length=20)),
                ('CEP', models.CharField(max_length=15)),
                ('imagem', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_consignado_emprestimo', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Valor_beneficio_renda_emprestimo', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Especie_de_beneficio_emprestimo', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('N_beneficio_matricula_emprestimo', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Margem_emprestimo', models.CharField(blank=True, max_length=20, null=True)),
                ('Banco_emprestimo', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Agencia_emprestimo', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Conta_emprestimo', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Tipo_da_conta_emprestimo', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('RG_emprestimo', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('CPF_emprestimo', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('Comprovante_emprestimo', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('Contra_cheque_emprestimo', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('nomes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nomes')),
            ],
        ),
        migrations.CreateModel(
            name='Consignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Bem_do_Financiamento', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=30, null=True)),
                ('Endereço_residencial_consignado', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Estado_do_Bem_consignado', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Entrada_consignado', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=30, null=True)),
                ('Banco_consignado', models.CharField(blank=True, default='Meu Banco', max_length=30, null=True)),
                ('Agencia_consignado', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Conta_consignado', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Tipo_da_conta_consignado', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('Conclusão_consignado', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=30, null=True)),
                ('Observação_consignado', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=30, null=True)),
                ('RG_consignado', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('CPF_consignado', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('Comprovante_consignado', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('IR_consignado', models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes)),
                ('nomes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nomes')),
            ],
        ),
    ]
