# Generated by Django 4.2.5 on 2023-09-25 18:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomes',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_imagem_nomes),
        ),
    ]
