from django.db import models

def upload_imagem_nomes(instance, filename):
    return f"{instance.Nome_completo}-{filename}"

class nomes(models.Model):
    Nome_completo = models.CharField(max_length=50)
    RG = models.CharField(max_length=20)
    CPF = models.CharField(max_length=20)
    Data_nascimento = models.CharField(max_length=15)
    Data_de_expedição = models.CharField(max_length=15)
    Orgão_emiçor = models.CharField(max_length=10)
    Estado_civil = models.CharField(max_length=10)
    Nome_da_Mãe = models.CharField(max_length=50)
    Empresa = models.CharField(max_length=20)
    Regime_de_trabalho = models.CharField(max_length=20)
    Profição = models.CharField(max_length=20)
    Salario_bruto = models.CharField(max_length=20)
    Salario_liquido = models.IntegerField()
    Endereço_residencial = models.CharField(max_length=50)
    Numero = models.CharField(max_length=10)
    Bairro = models.CharField(max_length=20)
    Cidade = models.CharField(max_length=20)
    Estado = models.CharField(max_length=20)
    CEP = models.CharField(max_length=15)
    imagem = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)

class consignado(models.Model):
    nomes = models.ForeignKey(nomes, on_delete=models.CASCADE)
    Status = models.CharField(max_length=30, default=None, null=True, blank=True)
    Bem_do_Financiamento = models.DecimalField(max_digits=30, decimal_places=2, default=None, null=True, blank=True)
    Endereço_residencial_consignado = models.CharField(max_length=30, default=None, null=True, blank=True)
    Estado_do_Bem_consignado = models.CharField(max_length=30, default=None, null=True, blank=True)
    Entrada_consignado = models.DecimalField(max_digits=30, decimal_places=2, default=None, null=True, blank=True)
    Banco_consignado = models.CharField(max_length=30, default='Meu Banco', null=True, blank=True)
    Agencia_consignado = models.CharField(max_length=30, default=None, null=True, blank=True)
    Conta_consignado = models.CharField(max_length=30, default=None, null=True, blank=True)
    Tipo_da_conta_consignado = models.DecimalField(max_digits=10, decimal_places=2, default=None, null=True, blank=True)
    Conclusão_consignado = models.DecimalField(max_digits=30, decimal_places=2, default=None, null=True, blank=True)
    Observação_consignado = models.DecimalField(max_digits=30, decimal_places=2, default=None, null=True, blank=True)
    RG_consignado = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)
    CPF_consignado = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)
    Comprovante_consignado = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)
    IR_consignado = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)

class emprestimo(models.Model):
    nomes = models.ForeignKey(nomes, on_delete=models.CASCADE)
    Tipo_de_consignado_emprestimo = models.CharField(max_length=30, default=None, null=True, blank=True)
    Valor_beneficio_renda_emprestimo = models.CharField(max_length=30, default=None, null=True, blank=True)
    Especie_de_beneficio_emprestimo = models.CharField(max_length=30, default=None, null=True, blank=True)
    N_beneficio_matricula_emprestimo = models.CharField(max_length=30, default=None, null=True, blank=True)
    Margem_emprestimo = models.CharField(max_length=20, null=True, blank=True)
    Banco_emprestimo = models.CharField(max_length=20, default=None, null=True, blank=True)
    Agencia_emprestimo = models.CharField(max_length=20, default=None, null=True, blank=True)
    Conta_emprestimo = models.CharField(max_length=20, default=None, null=True, blank=True)
    Tipo_da_conta_emprestimo = models.CharField(max_length=20, default=None, null=True, blank=True)
    RG_emprestimo = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)
    CPF_emprestimo = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)
    Comprovante_emprestimo = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)
    Contra_cheque_emprestimo = models.FileField(upload_to=upload_imagem_nomes, null=True, blank=True)
